### ISSUE TITLE
Chrome driver issues

### ISSUE THREAD

**Issue by quintendewilde** [adhikary97/TikTok-Bot#1]
python3 main.py --privacy Public --video_path /Users/quinten/Downloads/2018-05-09\ 15-40-38.mp4 --date_time 2021-03-21 --date_time 19:08 --caption helloworld
Traceback (most recent call last):
  File "/Users/quinten/tiktokbots/TikTok-Bot/main.py", line 103, in <module>
    main()
  File "/Users/quinten/tiktokbots/TikTok-Bot/main.py", line 99, in main
    TikTokBot(who_can_view=args.privacy, video_path=args.video_path, date_time=args.date_time, caption=args.caption)
  File "/Users/quinten/tiktokbots/TikTok-Bot/main.py", line 13, in __init__
    self.driver = webdriver.Chrome(f'{path}/chromedriver')
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 84

**Comment by freQuensy23-coder** [comment]
You should download Chrome version 84 or Chrome webdriver with the same version that Chrome
